name: 'Get & cache dependencies'
#on não é usado pois em actions não é um workflow
description: 'get dependencies via npm and cache them'

#inputs para controlar o fluxo de cada step
inputs:
  caching:
    description: 'escolha se vai realizar o cache ou não'
    required: false
    default: 'true'

#outputs para informações de fluxo
outputs:
  used-cache:
    description: 'cache was used'
    value: ${{ steps.install.outputs.cache }}
runs:
  using: 'composite'
  steps:
    #action que recupera dependencias e instala
    - name: Cache dependencies
      #contexto de input para recuperar os inputs declarados nessa action
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies

      #id utilizado para verificar se dependencias foram usadas
      id: install-dependencies

      #contexto de input para recuperar os inputs declarados nessa action
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: | 
        npm ci
        echo "cache='${{ inputs.caching }}" >> GITHUB_OUTPUT
      shell: bash #shell usado na action